// Ed25519 keypair + signing utilities for room host identity.
//
// Uses the Web Crypto SubtleCrypto API. Ed25519 is supported in
// Chrome 113+, Firefox 130+, Safari 17+, and Node.js 18+ (used by vitest).
//
// Private keys are generated as non-extractable CryptoKeys, so they
// cannot be exfiltrated by JS — they only exist inside the crypto
// subsystem and can only be used via sign().
//
// PR-3 addition: getOrCreateRoomHostKey() produces keys via HKDF derivation
// from room_host_seed_v1. Derived keys carry a `privateKeySeed` (32 raw bytes)
// instead of a WebCrypto CryptoKey — signing uses the @noble/curves path
// (ed25519.sign(msg, seed)) which accepts raw bytes directly.

import { ed25519 as nobleEd25519 } from '@noble/curves/ed25519.js';
import { toBase64url } from './base64url.js';
import { getOrCreateRoomHostSeed } from './room-host-seed.js';

export interface HostKeypair {
    publicKeyB64: string; // base64url, 32 bytes
    /**
     * Legacy WebCrypto private key (non-extractable). Present on keypairs
     * generated by generateHostKeypair(). Absent on HKDF-derived keypairs.
     */
    privateKey?: CryptoKey;
    /**
     * Raw 32-byte Ed25519 private seed for @noble/curves signing.
     * Present on HKDF-derived keypairs from getOrCreateRoomHostKey().
     * Absent on legacy WebCrypto keypairs from generateHostKeypair().
     * signHostAction() branches on this field.
     */
    privateKeySeed?: Uint8Array;
}

// Module-level cache: room_id → HostKeypair.
// CryptoKey cannot cross page navigations but same-page is fine.
export const hostKeypairCache = new Map<string, HostKeypair>();

export async function generateHostKeypair(): Promise<HostKeypair> {
    const kp = await crypto.subtle.generateKey(
        { name: 'Ed25519' } as unknown as AlgorithmIdentifier,
        false, // non-extractable
        ['sign', 'verify']
    );
    const pair = kp as CryptoKeyPair;
    const rawPub = await crypto.subtle.exportKey('raw', pair.publicKey);
    const publicKeyB64 = toBase64url(new Uint8Array(rawPub));
    return { publicKeyB64, privateKey: pair.privateKey };
}

/**
 * Sign a payload with a host keypair.
 *
 * Branches on which private key form is present in the HostKeypair:
 *   - privateKeySeed present → @noble/curves ed25519.sign() (raw-seed path,
 *     used by HKDF-derived keys from getOrCreateRoomHostKey).
 *   - privateKey present → WebCrypto subtle.sign() (non-extractable CryptoKey
 *     path, used by legacy generateHostKeypair keypairs).
 */
export async function signHostAction(
    key: HostKeypair,
    payload: string,
): Promise<string> {
    const enc = new TextEncoder();
    const msg = enc.encode(payload);

    if (key.privateKeySeed) {
        // @noble/curves path: raw 32-byte Ed25519 seed → sign directly.
        // Used by HKDF-derived keypairs (getOrCreateRoomHostKey).
        const sig = nobleEd25519.sign(msg, key.privateKeySeed);
        return toBase64url(sig);
    }

    if (key.privateKey) {
        // WebCrypto path: non-extractable CryptoKey.
        // Used by legacy generateHostKeypair() keypairs.
        const sig = await crypto.subtle.sign(
            { name: 'Ed25519' } as unknown as AlgorithmIdentifier,
            key.privateKey,
            msg,
        );
        return toBase64url(new Uint8Array(sig));
    }

    throw new Error('[host-identity] signHostAction: HostKeypair has neither privateKey nor privateKeySeed');
}

/** Fixed HKDF salt — an app constant; never changes after first use.
 *  Domain-separates the room-host KDF from any other HKDF consumer.
 *  31 ASCII bytes. (HKDF accepts any salt length; length is fixed and known.) */
const ROOM_HOST_HKDF_SALT = new TextEncoder().encode('oxpulse/room-host/salt/v1______');

/**
 * Derive the per-room host signing keypair from room_host_seed_v1.
 *
 * Deterministic: key = f(seed, roomId). Re-derivable any time, on any
 * device holding the seed — host authority survives a reload AND a device
 * change. The server only ever sees the per-room derived pubkey, which is
 * computationally unlinkable to the seed and to other rooms' pubkeys, so
 * room-to-room unlinkability is preserved.
 *
 * Derivation: HKDF-SHA256(ikm=seed, salt=ROOM_HOST_HKDF_SALT,
 *   info="oxpulse/room-host/v1/"+roomId, L=32) → Ed25519 private seed.
 */
export async function getOrCreateRoomHostKey(roomId: string): Promise<HostKeypair> {
    const seed = await getOrCreateRoomHostSeed();
    const ikm = await crypto.subtle.importKey('raw', seed as Uint8Array<ArrayBuffer>, { name: 'HKDF' }, false, ['deriveBits']);
    const info = new TextEncoder().encode(`oxpulse/room-host/v1/${roomId}`);
    const bits = await crypto.subtle.deriveBits(
        { name: 'HKDF', hash: 'SHA-256', salt: ROOM_HOST_HKDF_SALT, info },
        ikm,
        256, // 32 bytes
    );
    const privateKeySeed = new Uint8Array(bits);
    const pub = nobleEd25519.getPublicKey(privateKeySeed);
    return {
        publicKeyB64: toBase64url(pub),
        privateKeySeed,
    };
}

/// Stage B: Build kick payload with device pubkey targeting (instead of peer_id).
/// Format: `kick:{room_id}:{target_pubkey_b64}:{ts}`
export function buildKickPayload(roomId: string, targetPubkeyB64: string, ts: number): string {
    return `kick:${roomId}:${targetPubkeyB64}:${ts}`;
}

/// Stage B: Build lock payload (unchanged format, but host uses persistent identity).
/// Format: `lock:{room_id}:{ts}`
export function buildLockPayload(roomId: string, ts: number): string {
    return `lock:${roomId}:${ts}`;
}

/// Stage B: Build unlock payload.
/// Format: `unlock:{room_id}:{ts}`
export function buildUnlockPayload(roomId: string, ts: number): string {
    return `unlock:${roomId}:${ts}`;
}

/// Build pin-mint payload — format mirrors kick/lock (colon-separated).
/// Format: `pin-mint:{room_id}:{ts}` (ts = Unix seconds as integer)
export function buildPinMintPayload(roomId: string, ts: number): string {
    return `pin-mint:${roomId}:${ts}`;
}

/// Build shortlink-mint payload — ADR-0005 door 3 (Wave 4).
/// Domain prefix "shortlink-mint" distinguishes from "pin-mint" so a
/// PIN-mint signature cannot be replayed as a shortlink-mint and vice-versa.
///
/// Group kind-carrier binding (SEC-CR-001): when a group host mints WITH a
/// typed-10 `redirectRoomId`, that redirect is folded INTO the signed payload
/// (`shortlink-mint:{room_id}:{redirect}:{ts}`). This authenticates the
/// presence AND value of the redirect: an active MITM that strips the field
/// from the request makes the server verify `shortlink-mint:{room_id}:{ts}`
/// against a signature made over the redirect-inclusive form → mismatch → 403.
/// Without this binding, stripping the field silently falls back to the 9-char
/// `room_id` → `/s/<alias>` → bare-9 → mesh (the kind-carrier downgrade the
/// PR exists to fix, re-introduced over an unauthenticated channel).
///
/// Format (1:1 / no redirect):   `shortlink-mint:{room_id}:{ts}`
/// Format (group / w/ redirect): `shortlink-mint:{room_id}:{redirect}:{ts}`
/// ts = Unix seconds as integer. The no-redirect form is byte-identical to the
/// pre-binding format, so deployed 1:1 clients are unaffected.
export function buildShortlinkMintPayload(
    roomId: string,
    ts: number,
    redirectRoomId?: string,
): string {
    return redirectRoomId !== undefined
        ? `shortlink-mint:${roomId}:${redirectRoomId}:${ts}`
        : `shortlink-mint:${roomId}:${ts}`;
}
